### ISSUE TITLE
Login user

### ISSUE THREAD

**Issue by Mansiedi59** [ahnafhabibkhan/COVID-19-TRACKING-APP#1]

**Comment by TommySoucy** [comment]
Transaction to add new user:

INSERT INTO `soen390`.`user` (`UserID`, `Email`, `FirstName`, `LastName`, `Telephone`, `Address`, `Role`, `UserName`, `Password`) VALUES ('0', 'first@gmail.com', 'John', 'Smith', '4504664852', '7458 Main', 'User', 'JSmith', 'JSmith');

Do we want to store passwords as plain text or hash them?
