### ISSUE TITLE
As a user : Valid/invalid  user account input - Recovery username and password   

### ISSUE THREAD

**Issue by Mansiedi59** [ahnafhabibkhan/COVID-19-TRACKING-APP#13]
As a user I want to be able to recover my account (Username or password) 

Provide the API

**Comment by TommySoucy** [comment]
Considering email and password input fields are EmailLoginInput and PasswordLoginInput respectively, then this query would be used to get the corresponding user information:

```
select * from user where Email = EmailLoginInput;
```

This will give us access to the corresponding user's data.

So for login, we take the password from the data compare it to PasswordLoginInput.
If valid, we log them in.

For password recovery, if the query:

```
select count(*) from user where Email = EmailLoginInput;
```

return a value == 1, then we add an entry into the password request table with transaction:

```
INSERT INTO `soen390`.`passwordresetrequest` (`UserID`, `Key`) VALUES ('0', 'OM3V56');
```

For example. We then send an email to the user with that code (OM3V56). Either the code will be in a link they can follow directly, or they will be prompted to input that code directly in the same window as the request.

From there they will be prompted for a new password, and the new password will be entered in the DB with:

```
UPDATE `soen390`.`user` SET `Password` = 'JSmith0' WHERE (`UserID` = '0');
```

For example. From there they should be redirected to the login page and the entry should be removed from passwordresetrequest table using:

```
DELETE FROM `soen390`.`passwordresetrequest` WHERE (`UserID` = '0');
```
